### ISSUE TITLE
Question on uncertainty quantification

### ISSUE THREAD

**Issue by RobvanGastel** [python-adaptive/adaptive#448]
Hi authors!

I am exploring your package and like the simplicity of the implementation to adaptively sample search spaces. Are there any ideas on adding uncertainty quantification to the sampling strategies like you would have when using Gaussian processes for Bayesian optimization with a space-filling / expected improvement acquisition function? Any response on this would be much appreciated. Thank you very much for maintaining this project!

**Comment by akhmerov** [comment]
Hey @RobvanGastel!

In principle, we have a learner based on scikit-optimize, a GP-based optimization project. It is, however, archived and we intend to remove that learner from adaptive (see #404).

Overall GP is costly because of needing $O(N^3)$ operations to build from scratch and some lower power to update. Most of the adaptive built-in learners target a lower complexity, but the overall approach makes it sufficiently straightforward to implement Bayesian learners within the same API.

**Comment by RobvanGastel** [comment]
Hi Akhmerov, thank you for the fast answer. I wasn't aware of scikit-optimize being GP-based this is really helpful! Skopt is a good initial test for me to test your library.
